### ISSUE TITLE
[Feedback] python

### ISSUE THREAD

**Issue by woowonjin** [boostcamp-ai-tech-4/ai-tech-interview#139]
### ✅ 분야 선택

> 피드백을 주실 분야를 선택해주세요.

- [ ] Statistics/Math
- [ ] Machine Learning
- [ ] Deep Learning
- [x] Python
- [ ] Network
- [ ] Operating System
- [ ] Data Structure
- [ ] Algorithm

### ✍ 피드백 내용

> 저희도 공부하면서 작성한 내용이기 때문에 친절하게 알려주시면 감사하겠습니다!

- Python 10번 문제 정답 예시 주석에 global var이랑 local var이 반대로 되어있는것 같습니다!

**Comment by CoodingPenguin** [comment]
@woowonjin 수정 했습니다! 피드백 정말 감사드립니다😊
