### ISSUE TITLE
[Feedback] Statistics/Math #12

### ISSUE THREAD

**Issue by woowonjin** [boostcamp-ai-tech-4/ai-tech-interview#141]
### ✅ 분야 선택

> 피드백을 주실 분야를 선택해주세요.

- [x] Statistics/Math
- [ ] Machine Learning
- [ ] Deep Learning
- [ ] Python
- [ ] Network
- [ ] Operating System
- [ ] Data Structure
- [ ] Algorithm

### ✍ 피드백 내용

> 저희도 공부하면서 작성한 내용이기 때문에 친절하게 알려주시면 감사하겠습니다!

- 12번 엔트로피에서 "entropy는 데이터가 서로 다른 클래스에 속하면 높고, 같은 클래스에 속하면 낮다. 다시 말하면 각각의 데이터가 특정 클래스에 속할 확률이 높고 나머지 클래스에 속할 확률이 낮다면 entropy가 높고, 모든 각각의 클래스에 속할 확률이 비슷하다면 entropy는 낮다." 라는 문장이 있는데, 여기서 모든 각각의 클래스에 속할 확률이 비슷하다면 entropy는 큰것 아닌가여??.. 제가 잘못 알고있다면 죄송합니다..!!
- 그리고 그 다음에 "information gain은 어떤 속성을 선택함으로 인해 데이터가 잘 필터링되는지를 말하며, 1에서 엔트로피를 뺀 값으로 표현된다." 라는 문장이 나오는데 1에서 엔트로피를 빼는것이 아니라 이전 상태의 엔트로피에서 현재 상태의 엔트로피를 빼는것이 아닌가여?? 이것두 제가 잘못 알고있다면.. ㅠㅠㅠ 확인 부탁드립니다 !!

**Comment by Heeseok-Jeong** [comment]
안녕하세요 우진님 :)

두 개 다 우진님 말씀이 맞습니다!  내용은 수정해서 커밋했습니다.

감사합니다!
부캠도 화이팅입니다 ㅎㅎ
