### ISSUE TITLE
[Feedback] Deep Learning #12-3

### ISSUE THREAD

**Issue by woowonjin** [boostcamp-ai-tech-4/ai-tech-interview#142]
### 📌 분야/번호
- `분야`: Deep Learning
- `번호`: 12-3

### ✍  피드백 내용

> 저희도 공부하면서 작성한 내용이기 때문에 친절하게 알려주시면 감사하겠습니다!

- ReLU의 문제점에서 "이를 해결하기 위해 배치 정규화(Batch Normalization)을 사용하여 결과값의 평균이 0이 되도록 하거나" 라는 문장이 있는데 Batch Normalization을 사용한다고 해서 평균이 0이 되는것은 아니지 않나여??.. gamma, beta를 학습해서 분포를 구한다고 생각해서 beta에 따라 평균이 달라진다고 생각합니다.!! 혹시 제가 잘못 알고있는 것이라면 피드백 부탁드립니다.!!

**Comment by Heeseok-Jeong** [comment]
음 그렇네요. 베타를 쓰면 좌우 이동이 되니까요.

수정하겠습니다 :)

감사합니다.
