### ISSUE TITLE
[피드백] Machine Learning #14

### ISSUE THREAD

**Issue by sunwoongc** [boostcamp-ai-tech-4/ai-tech-interview#176]
📌 분야/번호

분야: Machine Learning
번호: 14
✍ 피드백 내용

뉴턴 메소드를 설명하는 부분에서 해를 근사적으로 찾는 뉴턴 메소드에서 설명을 해주고 있습니다. 하지만 해당 질문에서는 최적화 방법에서의 뉴턴 메소드에 대해서 묻고 있기 때문에, 2차 테일러 근사를 이용해 최적화 값을 찾는 방법을 언급해주는 것이 더 맞다고 생각이 듭니다!

* cs231n에도 한번 언급이 됐던 내용이고, '최적화 뉴턴 방법' 과 같은 키워드로 검색하면 좋은 자료들이 많이 나옵니다!

* 별도로 라벨이나, 이슈를 쓰는 템플릿을 어떻게 찾아야 하는 지 몰라서 다른 분들의 양식을 복붙해왔습니다!

**Comment by CoodingPenguin** [comment]
@changwoomon 다시 리마인드 드립니다

**Comment by CoodingPenguin** [comment]
답변 수정되었습니다. 수정된 답변 참고 바랍니다:)
